// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBte153mzuZp4PdPZH91NLvY9C54npitik',
    appId: '1:369315054500:web:68e534f4d7e9b0a80d3731',
    messagingSenderId: '369315054500',
    projectId: 'my-chat-app-fd76a',
    authDomain: 'my-chat-app-fd76a.firebaseapp.com',
    storageBucket: 'my-chat-app-fd76a.appspot.com',
    measurementId: 'G-FK0WRH8DL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJM2SCUzW6R2Is7nEZqhuE90SubL5JEE',
    appId: '1:369315054500:android:2dc5a5e124b8b2300d3731',
    messagingSenderId: '369315054500',
    projectId: 'my-chat-app-fd76a',
    storageBucket: 'my-chat-app-fd76a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPixCNtLyJ6Mnd9mYJxZNPjTGVjKb05K0',
    appId: '1:369315054500:ios:608c7a607d4eb7960d3731',
    messagingSenderId: '369315054500',
    projectId: 'my-chat-app-fd76a',
    storageBucket: 'my-chat-app-fd76a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPixCNtLyJ6Mnd9mYJxZNPjTGVjKb05K0',
    appId: '1:369315054500:ios:608c7a607d4eb7960d3731',
    messagingSenderId: '369315054500',
    projectId: 'my-chat-app-fd76a',
    storageBucket: 'my-chat-app-fd76a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBte153mzuZp4PdPZH91NLvY9C54npitik',
    appId: '1:369315054500:web:67154fac99c0b24e0d3731',
    messagingSenderId: '369315054500',
    projectId: 'my-chat-app-fd76a',
    authDomain: 'my-chat-app-fd76a.firebaseapp.com',
    storageBucket: 'my-chat-app-fd76a.appspot.com',
    measurementId: 'G-RHDZFLSHVB',
  );
}
